baseURL = 'https://sahb4k.github.io'
languageCode = 'en-us'
title = 'Security Research'
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  disableHomeInfo = false
  ShowReadingTime = true
  ShowToc = true
  defaultTheme = "auto"   # light/dark mode auto
   [params.homeInfoParams]
     Title = "Security Research"
     Content = "Welcome to my blog on offensive security, CTFs, and more."

[taxonomies]
  tag = "tags"         # offensive/security tags and general tags
  category = "categories"  # general grouping if needed
  platform = "platforms"   # HTB, THM, CTF
  difficulty = "difficulties"  # Easy, Medium, Hard

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Writeups"
  url = "/writeups/"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 4

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5
