baseURL = 'https://sahb4k.github.io'
languageCode = 'en-us'
title = 'Security Research'
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime = true
  ShowToc = true
  defaultTheme = "auto"   # light/dark mode auto
  [params.homeInfoParams]
    Title = "Security Research"
    Content = "Welcome to my blog on offensive security, CTFs, and more."
  [params.profileMode]
    enabled = true
    title = "Security Research"
    subtitle = "Hover over menu items to see previews."
    imageUrl = "/images/nav/home.webp"  # Default home background
    imageWidth = 120
    imageTitle = "Home Background"

[taxonomies]
  tag = "tags"         # offensive/security tags and general tags
  category = "categories"  # general grouping if needed
  platform = "platforms"   # HTB, THM, CTF
  difficulty = "difficulties"  # Easy, Medium, Hard

# Top menu: we include a small `bg` parameter for each item for the hover-bg
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
  [menu.main.params]
    bg = "/images/nav/home.webp"

[[menu.main]]
  name = "Writeups"
  url = "/writeups/"
  weight = 2
  [menu.main.params]
    bg = "/images/nav/writeups.webp"

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3
  [menu.main.params]
    bg = "/images/nav/projects.webp"

[[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 4
  [menu.main.params]
    bg = "/images/nav/services.webp"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 5
  [menu.main.params]
    bg = "/images/nav/about.webp"
